environments:
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  quarkus-main:
    enabled: false
    env_vars:
      QUARKUS_BRANCH: main
    ids:
    - quarkus
  quarkus-branch:
    env_vars:
      QUARKUS_BRANCH: '2.16'
    ids:
    - quarkus
  ecosystem:
    auto_generation: false
    ids:
    - ecosystem
repositories:
- name: incubator-kie-optaplanner
  job_display_name: optaplanner
  branch: 8.45.x
  is_branch_config_repo: true
- name: incubator-kie-optaplanner-quickstarts
  job_display_name: optaplanner-quickstarts
  branch: 8.45.x
git:
  author:
    name: apache
    credentials_id: 399061d0-5ab5-4142-a186-a52081fef742
    token_credentials_id: ci-builds
    push:
      credentials_id: 84811880-2025-45b6-a44c-2f33bef30ad2
      token_credentials_id: 41128c14-bb63-4708-9074-d20a318ee630
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
    push:
      credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: incubator-kie-optaplanner
    file_path: .ci/buildchain-config.yaml
    token_credentials_id: kie-ci3-token
maven:
  settings_file_id: kie-release-settings
  nexus:
    release_url: TO_DEFINE
    release_repository: TO_DEFINE
    staging_profile_url: TO_DEFINE
    staging_profile_id: TO_DEFINE
    build_promotion_profile_id: TO_DEFINE
  artifacts_repository: ''
  artifacts_upload_repository:
    url: https://repository.apache.org/content/repositories/snapshots
    creds_id: apache-nexus-kie-deploy-credentials
cloud:
  image:
    registry_credentials: tradisso_registry_token
    registry: quay.io
    namespace: tradisso
    latest_git_branch: main
jenkins:
  email_creds_id: OPTAPLANNER_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        image: quay.io/kiegroup/kogito-ci-build:main-latest
        args: --privileged --group-add docker
  default_tools:
    jdk: jdk_17_latest
    maven: maven_3.8.6
    sonar_jdk: jdk_17_latest
